interface CountryData {
  flag: string;
  name: string;
  capital: string;
  population: string;
  subRegion: string;
  languagesCount: string;
  currency: string;
  currencySymbol: string;
}

const africanCountries: CountryData[] = [
  {
    flag: "🇩🇿",
    name: "Algeria",
    capital: "Algiers",
    population: "45,606,480",
    subRegion: "Northern Africa",
    languagesCount: "2",
    currency: "Algerian Dinar",
    currencySymbol: "DZD",
  },
  {
    flag: "🇦🇴",
    name: "Angola",
    capital: "Luanda",
    population: "36,684,202",
    subRegion: "Middle Africa",
    languagesCount: "10+",
    currency: "Angolan Kwanza",
    currencySymbol: "AOA",
  },
  {
    flag: "🇧🇯",
    name: "Benin",
    capital: "Porto-Novo",
    population: "13,301,694",
    subRegion: "Western Africa",
    languagesCount: "50+",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
  },
  {
    flag: "🇧🇼",
    name: "Botswana",
    capital: "Gaborone",
    population: "2,658,806",
    subRegion: "Southern Africa",
    languagesCount: "2",
    currency: "Botswana Pula",
    currencySymbol: "BWP",
  },
  {
    flag: "🇧🇫",
    name: "Burkina Faso",
    capital: "Ouagadougou",
    population: "22,100,683",
    subRegion: "Western Africa",
    languagesCount: "70+",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
  },
  {
    flag: "🇧🇮",
    name: "Burundi",
    capital: "Gitega",
    population: "13,238,559",
    subRegion: "Eastern Africa",
    languagesCount: "3",
    currency: "Burundian Franc",
    currencySymbol: "BIF",
  },
  {
    flag: "🇨🇻",
    name: "Cabo Verde",
    capital: "Praia",
    population: "555,987",
    subRegion: "Western Africa",
    languagesCount: "2",
    currency: "Cape Verdean Escudo",
    currencySymbol: "CVE",
  },
  {
    flag: "🇨🇲",
    name: "Cameroon",
    capital: "Yaoundé",
    population: "28,647,293",
    subRegion: "Middle Africa",
    languagesCount: "250+",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
  },
  {
    flag: "🇨🇫",
    name: "Central African Republic",
    capital: "Bangui",
    population: "5,990,855",
    subRegion: "Middle Africa",
    languagesCount: "80+",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
  },
  {
    flag: "🇹🇩",
    name: "Chad",
    capital: "N'Djamena",
    population: "17,179,740",
    subRegion: "Middle Africa",
    languagesCount: "120+",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
  },
  {
    flag: "🇰🇲",
    name: "Comoros",
    capital: "Moroni",
    population: "869,601",
    subRegion: "Eastern Africa",
    languagesCount: "3",
    currency: "Comorian Franc",
    currencySymbol: "KMF",
  },
  {
    flag: "🇨🇩",
    name: "Democratic Republic of the Congo",
    capital: "Kinshasa",
    population: "109,276,265",
    subRegion: "Middle Africa",
    languagesCount: "200+",
    currency: "Congolese Franc",
    currencySymbol: "FC",
  },
  {
    flag: "🇩🇯",
    name: "Djibouti",
    capital: "Djibouti",
    population: "1,134,631",
    subRegion: "Eastern Africa",
    languagesCount: "3",
    currency: "Djiboutian Franc",
    currencySymbol: "DJF",
  },
  {
    flag: "🇪🇬",
    name: "Egypt",
    capital: "Cairo",
    population: "116,538,258",
    subRegion: "Northern Africa",
    languagesCount: "1",
    currency: "Egyptian Pound",
    currencySymbol: "£",
  },
  {
    flag: "🇬🇶",
    name: "Equatorial Guinea",
    capital: "Malabo",
    population: "1,634,222",
    subRegion: "Middle Africa",
    languagesCount: "3",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
  },
  {
    flag: "🇪🇷",
    name: "Eritrea",
    capital: "Asmara",
    population: "3,748,901",
    subRegion: "Eastern Africa",
    languagesCount: "9",
    currency: "Eritrean Nakfa",
    currencySymbol: "ERN",
  },
  {
    flag: "🇪🇹",
    name: "Ethiopia",
    capital: "Addis Ababa",
    population: "132,059,767",
    subRegion: "Eastern Africa",
    languagesCount: "80+",
    currency: "Ethiopian Birr",
    currencySymbol: "Br",
  },
  {
    flag: "🇬🇦",
    name: "Gabon",
    capital: "Libreville",
    population: "2,441,333",
    subRegion: "Middle Africa",
    languagesCount: "40+",
    currency: "Central African CFA Franc",
    currencySymbol: "CFA",
  },
  {
    flag: "🇬🇲",
    name: "Gambia",
    capital: "Banjul",
    population: "2,705,992",
    subRegion: "Western Africa",
    languagesCount: "10+",
    currency: "Gambian Dalasi",
    currencySymbol: "GMD",
  },
  {
    flag: "🇬🇭",
    name: "Ghana",
    capital: "Accra",
    population: "34,121,985",
    subRegion: "Western Africa",
    languagesCount: "80+",
    currency: "Ghanaian Cedi",
    currencySymbol: "GHS",
  },
  {
    flag: "🇬🇳",
    name: "Guinea",
    capital: "Conakry",
    population: "14,186,078",
    subRegion: "Western Africa",
    languagesCount: "30+",
    currency: "Guinean Franc",
    currencySymbol: "GNF",
  },
  {
    flag: "🇰🇪",
    name: "Kenya",
    capital: "Nairobi",
    population: "55,100,586",
    subRegion: "Eastern Africa",
    languagesCount: "68",
    currency: "Kenyan Shilling",
    currencySymbol: "KES",
  },
  {
    flag: "🇱🇾",
    name: "Libya",
    capital: "Tripoli",
    population: "6,812,341",
    subRegion: "Northern Africa",
    languagesCount: "3",
    currency: "Libyan Dinar",
    currencySymbol: "LYD",
  },
  {
    flag: "🇲🇬",
    name: "Madagascar",
    capital: "Antananarivo",
    population: "30,639,516",
    subRegion: "Eastern Africa",
    languagesCount: "18",
    currency: "Malagasy Ariary",
    currencySymbol: "MGA",
  },
  {
    flag: "🇲🇼",
    name: "Malawi",
    capital: "Lilongwe",
    population: "21,197,485",
    subRegion: "Eastern Africa",
    languagesCount: "12",
    currency: "Malawian Kwacha",
    currencySymbol: "MWK",
  },
  {
    flag: "🇲🇱",
    name: "Mali",
    capital: "Bamako",
    population: "22,188,380",
    subRegion: "Western Africa",
    languagesCount: "70+",
    currency: "West African CFA Franc",
    currencySymbol: "CFA",
  },

  {
    flag: "🇳🇬",
    name: "Nigeria",
    capital: "Abuja",
    population: "232,679,478",
    subRegion: "Western Africa",
    languagesCount: "645",
    currency: "Nigerian Naira",
    currencySymbol: "₦",
  },
  {
    flag: "🇿🇦",
    name: "South Africa",
    capital:
      "Pretoria (Executive), Bloemfontein (Judicial), Cape Town (Legislative)",
    population: "59,392,400",
    subRegion: "Southern Africa",
    languagesCount: "11",
    currency: "South African Rand",
    currencySymbol: "R",
  },
  {
    flag: "🇺🇬",
    name: "Uganda",
    capital: "Kampala",
    population: "47,249,585",
    subRegion: "Eastern Africa",
    languagesCount: "40+",
    currency: "Ugandan Shilling",
    currencySymbol: "UGX",
  },
  {
    flag: "🇿🇲",
    name: "Zambia",
    capital: "Lusaka",
    population: "20,017,746",
    subRegion: "Eastern Africa",
    languagesCount: "72",
    currency: "Zambian Kwacha",
    currencySymbol: "ZMW",
  },
  {
    flag: "🇿🇼",
    name: "Zimbabwe",
    capital: "Harare",
    population: "16,512,629",
    subRegion: "Eastern Africa",
    languagesCount: "16",
    currency: "Zimbabwean Dollar",
    currencySymbol: "ZWL",
  },
];

export default africanCountries;
