interface CountryData {
  flag: string;
  name: string;
  capital: string;
  population: string;
  subRegion: string;
  languagesCount: string;
  currency: string;
  currencySymbol: string;
  traditionalClothing?: string;
}

const africanCountries: CountryData[] = [
  {
    flag: "🇩🇿",
    name: "Algeria",
    capital: "Algiers",
    population: "46,814,308",
    subRegion: "Northern Africa",
    languagesCount: "Over 30",
    currency: "Algerian Dinar (DZD)",
    currencySymbol: "دج",
    traditionalClothing: "Karakou",
  },
  {
    flag: "🇦🇴",
    name: "Angola",
    capital: "Luanda",
    population: "37,885,849",
    subRegion: "Middle Africa",
    languagesCount: "46",
    currency: "Angolan Kwanza (AOA)",
    currencySymbol: "Kz",
    traditionalClothing: "Samakaka",
  },
  {
    flag: "🇧🇯",
    name: "Benin",
    capital: "Porto-Novo",
    population: "14,462,724",
    subRegion: "Western Africa",
    languagesCount: "55",
    currency: "West African CFA Franc (XOF)",
    currencySymbol: "F.CFA",
    traditionalClothing: "Aso Oke",
  },
  {
    flag: "🇧🇼",
    name: "Botswana",
    capital: "Gaborone",
    population: "2,521,139",
    subRegion: "Southern Africa",
    languagesCount: "Approx. 31",
    currency: "Botswana Pula (BWP)",
    currencySymbol: "P",
    traditionalClothing: "Leteisi/Shweshwe",
  },
  {
    flag: "🇧🇫",
    name: "Burkina Faso",
    capital: "Ouagadougou",
    population: "23,548,781",
    subRegion: "Western Africa",
    languagesCount: "Approx. 70",
    currency: "West African CFA Franc (XOF)",
    currencySymbol: "F.CFA",
    traditionalClothing: "Faso Dan Fani",
  },
  {
    flag: "🇧🇮",
    name: "Burundi",
    capital: "Gitega",
    population: "14,047,786",
    subRegion: "Eastern Africa",
    languagesCount: "3",
    currency: "Burundian Franc (BIF)",
    currencySymbol: "Fbu",
    traditionalClothing: "Imikenke",
  },
  {
    flag: "🇨🇻",
    name: "Cabo Verde (Cape Verde)",
    capital: "Praia",
    population: "524,877",
    subRegion: "Western Africa",
    languagesCount: "2",
    currency: "Cape Verdean Escudo (CVE)",
    currencySymbol: "Esc or $",
    traditionalClothing: "Panos",
  },
  {
    flag: "🇨🇲",
    name: "Cameroon",
    capital: "Yaoundé",
    population: "29,123,744",
    subRegion: "Middle Africa",
    languagesCount: "Approx. 280",
    currency: "Central African CFA Franc (XAF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Toghu",
  },
  {
    flag: "🇨🇫",
    name: "Central African Republic",
    capital: "Bangui",
    population: "5,330,690",
    subRegion: "Middle Africa",
    languagesCount: "Approx. 70",
    currency: "Central African CFA Franc (XAF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Bark Cloth",
  },
  {
    flag: "🇹🇩",
    name: "Chad",
    capital: "N'Djamena",
    population: "20,299,123",
    subRegion: "Middle Africa",
    languagesCount: "Approx. 120",
    currency: "Central African CFA Franc (XAF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Raphia Fabric",
  },
  {
    flag: "🇰🇲",
    name: "Comoros",
    capital: "Moroni",
    population: "866,628",
    subRegion: "Eastern Africa",
    languagesCount: "8",
    currency: "Comorian Franc (KMF)",
    currencySymbol: "KMF",
    traditionalClothing: "Leso",
  },
  {
    flag: "🇨🇩",
    name: "Congo (Republic)",
    capital: "Brazzaville",
    population: "6,332,961",
    subRegion: "Middle Africa",
    languagesCount: "Over 200",
    currency: "Central African CFA Franc (XAF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Kuba Cloth",
  },
  {
    flag: "🇩🇩",
    name: "Congo (Democratic Republic)",
    capital: "Kinshasa",
    population: "109,276,265",
    subRegion: "Middle Africa",
    languagesCount: "Approx. 215",
    currency: "Congolese Franc (CDF)",
    currencySymbol: "FC",
    traditionalClothing: "Kuba Raffia",
  },
  {
    flag: "🇩🇯",
    name: "Djibouti",
    capital: "Djibouti",
    population: "1,168,722",
    subRegion: "Eastern Africa",
    languagesCount: "Approx. 4",
    currency: "Djiboutian Franc (DJF)",
    currencySymbol: "Fdj",
    traditionalClothing: "Dirac",
  },
  {
    flag: "🇪🇬",
    name: "Egypt",
    capital: "Cairo",
    population: "116,538,258",
    subRegion: "Northern Africa",
    languagesCount: "Approx. 16",
    currency: "Egyptian Pound (EGP)",
    currencySymbol: "EGP, E£, LE",
    traditionalClothing: "Kilim",
  },
  {
    flag: "🇬🇶",
    name: "Equatorial Guinea",
    capital: "Malabo",
    population: "1,892,516",
    subRegion: "Middle Africa",
    languagesCount: "Approx. 14",
    currency: "Central African CFA Franc (XAF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Ndop Cloth",
  },
  {
    flag: "🇪🇷",
    name: "Eritrea",
    capital: "Asmara",
    population: "3,535,603",
    subRegion: "Eastern Africa",
    languagesCount: "Over 9",
    currency: "Eritrean Nakfa (ERN)",
    currencySymbol: "Nkf",
    traditionalClothing: "Habesha Kemis",
  },
  {
    flag: "🇪🇹",
    name: "Ethiopia",
    capital: "Addis Ababa",
    population: "132,059,767",
    subRegion: "Eastern Africa",
    languagesCount: "Approx. 116",
    currency: "Ethiopian Birr (ETB)",
    currencySymbol: "Br or ብር",
    traditionalClothing: "Habesha Kemis",
  },
  {
    flag: "🇬🇦",
    name: "Gabon",
    capital: "Libreville",
    population: "2,538,952",
    subRegion: "Middle Africa",
    languagesCount: "Approx. 50",
    currency: "Central African CFA Franc (XAF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Raffia",
  },
  {
    flag: "🇬🇲",
    name: "Gambia",
    capital: "Banjul",
    population: "2,759,988",
    subRegion: "Western Africa",
    languagesCount: "Over 10",
    currency: "Gambian Dalasi (GMD)",
    currencySymbol: "Br or ብር",
    traditionalClothing: "Kente",
  },
  {
    flag: "🇬🇭",
    name: "Ghana",
    capital: "Accra",
    population: "34,427,414",
    subRegion: "Western Africa",
    languagesCount: "Approx. 82",
    currency: "Ghanaian Cedi (GHS)",
    currencySymbol: "D",
    traditionalClothing: "Kente/Adinkra",
  },
  {
    flag: "🇬🇳",
    name: "Guinea",
    capital: "Conakry",
    population: "14,000,000",
    subRegion: "Western Africa",
    languagesCount: "Approx. 24",
    currency: "Guinean Franc (GNF)",
    currencySymbol: "GNF",
    traditionalClothing: "Fouta",
  },
  {
    flag: "🇬🇼",
    name: "Guinea-Bissau",
    capital: "Bissau",
    population: "1,999,000",
    subRegion: "Western Africa",
    languagesCount: "6",
    currency: "Guinea-Bissau Peso (GWP)",
    currencySymbol: "GWP",
    traditionalClothing: "Panu",
  },
  {
    flag: "🇬🇳",
    name: "Guinea",
    capital: "Conakry",
    population: "13,080,000",
    subRegion: "Western Africa",
    languagesCount: "Approx. 24",
    currency: "Guinean Franc",
    currencySymbol: "GNF",
    traditionalClothing: "Fouta",
  },
  {
    flag: "🇬🇶",
    name: "Equatorial Guinea",
    capital: "Malabo",
    population: "1,892,516",
    subRegion: "Middle Africa",
    languagesCount: "Approx. 14",
    currency: "Central African CFA Franc (XAF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Ndop Cloth",
  },
  {
    flag: "🇮🇬",
    name: "Gabon",
    capital: "Libreville",
    population: "2,538,952",
    subRegion: "Middle Africa",
    languagesCount: "Approx. 50",
    currency: "Central African CFA Franc (XAF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Raffia",
  },
  {
    flag: "🇬🇲",
    name: "Gambia",
    capital: "Banjul",
    population: "2,759,988",
    subRegion: "Western Africa",
    languagesCount: "Over 10",
    currency: "Gambian Dalasi (GMD)",
    currencySymbol: "D",
    traditionalClothing: "Kente",
  },
  {
    flag: "🇬🇭",
    name: "Ghana",
    capital: "Accra",
    population: "34,427,414",
    subRegion: "Western Africa",
    languagesCount: "Approx. 82",
    currency: "Ghanaian Cedi (GHS)",
    currencySymbol: "₵",
    traditionalClothing: "Kente/Adinkra",
  },
  {
    flag: "🇬🇳",
    name: "Guinea",
    capital: "Conakry",
    population: "13,080,000",
    subRegion: "Western Africa",
    languagesCount: "Approx. 24",
    currency: "Guinean Franc (GNF)",
    currencySymbol: "GNF",
    traditionalClothing: "Fouta",
  },
  {
    flag: "🇬🇼",
    name: "Guinea-Bissau",
    capital: "Bissau",
    population: "1,999,000",
    subRegion: "Western Africa",
    languagesCount: "6",
    currency: "Guinea-Bissau Peso (GWP)",
    currencySymbol: "GWP",
    traditionalClothing: "Panu",
  },
  {
    flag: "🇰🇪",
    name: "Kenya",
    capital: "Nairobi",
    population: "54,985,698",
    subRegion: "Eastern Africa",
    languagesCount: "Approx. 68",
    currency: "Kenyan Shilling (KES)",
    currencySymbol: "KSh",
    traditionalClothing: "Shuka",
  },
  {
    flag: "🇱🇸",
    name: "Lesotho",
    capital: "Maseru",
    population: "2,142,249",
    subRegion: "Southern Africa",
    languagesCount: "2",
    currency: "Lesotho Loti (LSL)",
    currencySymbol: "M",
    traditionalClothing: "Mokorotlo",
  },
  {
    flag: "🇱🇸",
    name: "Liberia",
    capital: "Monrovia",
    population: "5,053,000",
    subRegion: "Western Africa",
    languagesCount: "Approx. 17",
    currency: "Liberian Dollar (LRD)",
    currencySymbol: "$",
    traditionalClothing: "Lappa",
  },
  {
    flag: "🇪🇱",
    name: "Sierra Leone",
    capital: "Freetown",
    population: "7,813,000",
    subRegion: "Western Africa",
    languagesCount: "Approx. 15",
    currency: "Sierra Leonean Leone (SLL)",
    currencySymbol: "Le",
    traditionalClothing: "Gele",
  },
  {
    flag: "🇸🇹",
    name: "São Tomé and Príncipe",
    capital: "São Tomé",
    population: "219,159",
    subRegion: "Middle Africa",
    languagesCount: "2",
    currency: "São Tomé and Príncipe Dobra (STN)",
    currencySymbol: "Db",
    traditionalClothing: "Lesse",
  },
  {
    flag: "🇸🇳",
    name: "Senegal",
    capital: "Dakar",
    population: "17,193,000",
    subRegion: "Western Africa",
    languagesCount: "Approx. 10",
    currency: "West African CFA Franc (XOF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Boubou",
  },
  {
    flag: "🇸🇩",
    name: "Sudan",
    capital: "Khartoum",
    population: "42,810,000",
    subRegion: "Northern Africa",
    languagesCount: "Approx. 70",
    currency: "Sudanese Pound (SDG)",
    currencySymbol: "ج.س",
    traditionalClothing: "Jalabiya",
  },
  {
    flag: "🇸🇿",
    name: "Eswatini (formerly Swaziland)",
    capital: "Mbabane",
    population: "1,127,000",
    subRegion: "Southern Africa",
    languagesCount: "2",
    currency: "Lilangeni (SZL)",
    currencySymbol: "E",
    traditionalClothing: "Sidvwaba",
  },
  {
    flag: "🇹🇿",
    name: "Tanzania",
    capital: "Dodoma",
    population: "68,007,000",
    subRegion: "Eastern Africa",
    languagesCount: "Approx. 120",
    currency: "Tanzanian Shilling (TZS)",
    currencySymbol: "TSh",
    traditionalClothing: "Kitenge",
  },
  {
    flag: "🇹🇬",
    name: "Togo",
    capital: "Lomé",
    population: "8,191,000",
    subRegion: "Western Africa",
    languagesCount: "Over 40",
    currency: "West African CFA Franc (XOF)",
    currencySymbol: "FCFA",
    traditionalClothing: "Kente",
  },
  {
    flag: "🇺🇬",
    name: "Uganda",
    capital: "Kampala",
    population: "45,850,000",
    subRegion: "Eastern Africa",
    languagesCount: "Over 40",
    currency: "Ugandan Shilling (UGX)",
    currencySymbol: "USh",
    traditionalClothing: "Kanzu",
  },
  {
    flag: "🇿🇦",
    name: "South Africa",
    capital:
      "Pretoria (administrative), Cape Town (legislative), Bloemfontein (judicial)",
    population: "58,775,022",
    subRegion: "Southern Africa",
    languagesCount: "11",
    currency: "South African Rand (ZAR)",
    currencySymbol: "R",
    traditionalClothing: "Shweshwe",
  },
  {
    flag: "🇿🇼",
    name: "Zimbabwe",
    capital: "Harare",
    population: "15,122,000",
    subRegion: "Southern Africa",
    languagesCount: "16",
    currency: "Zimbabwean Dollar (ZWL)",
    currencySymbol: "$",
    traditionalClothing: "Zunde",
  },
];

export default africanCountries;
